public class MathOperation {
    public static void addMethod(integer x, integer y, integer z){
        system.debug('Add Result--->'+(x+y+z));
    }
    public static void subMethod(integer x, integer y){
        system.debug('Sub Result--->'+(x-y));
    }
    public static void mulMethod(integer x, integer y){
        system.debug('Mul Result--->'+(x*y));
    }
    public static void divMethod(integer x, integer y){
        system.debug('Div Result--->'+(x/y));
    }
    public static integer multiplyMethod(integer x, integer y){
        return (x*y);
}
}