public class MathOp {
    public void Addition(integer x, integer y){
        System.debug('Addition result:'+(x+y));
    }
    public void Subtraction(integer x, integer y){
        System.debug('Subtraction result:'+(x+y));
    }
    public void Multiplication(integer x, integer y){
        System.debug('Multiplication result:'+(x+y));
    }
    public void Division(integer x, integer y){
        System.debug('Division result:'+(x+y));
    }
}